export { checklistAPI }       from './checklist'
export { gradesAPI }          from './grades'
export { activitiesAPI }      from './activities'
export { counselingAPI }      from './counseling'
export { analysisAPI }        from './analysis'
export { studyPlanAPI }       from './studyPlan'
export { recommendationsAPI } from './recommendations'
export { notificationsAPI }   from './notifications'
export { reviewAPI }          from './review'
export { wrongAnswerAPI }     from './wrongAnswer'
export { authAPI }            from './auth'
export { aiReportAPI }        from './aiReport'
export { studentAPI }         from './student'
export { boardAPI }           from './board'
export const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8080'